// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteAplicacao.Infraestructure.Context;

#nullable disable

namespace TesteAplicacao.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20250620134831_mssql.onprem_migration_275")]
    partial class mssqlonprem_migration_275
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteAplicacao.Entities.Conta", b =>
                {
                    b.Property<long>("conta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("conta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("conta_id"));

                    b.Property<bool>("ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("banco");

                    b.Property<DateTime?>("data_criacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero");

                    b.Property<decimal>("saldo_disponivel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_disponivel");

                    b.Property<decimal>("saldo_pendente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_pendente");

                    b.Property<decimal>("saldo_total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_total");

                    b.Property<long>("usuario_id")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("conta_id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Produto", b =>
                {
                    b.Property<long>("produto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("produto_id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("data_compra")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_compra");

                    b.Property<DateTime?>("datahora_insercao")
                        .HasColumnType("datetime2")
                        .HasColumnName("datahora_insercao");

                    b.Property<string>("descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<long>("raridade")
                        .HasColumnType("bigint")
                        .HasColumnName("raridade");

                    b.Property<long>("usuario_id")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("produto_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("TesteAplicacao.Entities.TransacaoConta", b =>
                {
                    b.Property<long>("transacao_conta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transacao_conta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("transacao_conta_id"));

                    b.Property<long>("conta_id")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_id");

                    b.Property<long?>("conta_id1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datahora_transacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("datahora");

                    b.Property<string>("descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("transacao_conta_id");

                    b.HasIndex("conta_id");

                    b.HasIndex("conta_id1");

                    b.ToTable("transacao_conta", (string)null);
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Usuario", b =>
                {
                    b.Property<long>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("usuario_id"));

                    b.Property<bool>("ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("datahora_desativacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("datahora_desativacao");

                    b.Property<DateTime?>("datahora_insercao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("datahora_insercao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<byte[]>("senha_hash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("senha_hash");

                    b.Property<byte[]>("senha_salt")
                        .IsRequired()
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("senha_salt");

                    b.Property<string>("telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefone");

                    b.HasKey("usuario_id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Conta", b =>
                {
                    b.HasOne("TesteAplicacao.Entities.Usuario", "Usuario")
                        .WithOne("Conta")
                        .HasForeignKey("TesteAplicacao.Entities.Conta", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Produto", b =>
                {
                    b.HasOne("TesteAplicacao.Entities.Usuario", "usuario")
                        .WithMany("produtos")
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TesteAplicacao.Entities.TransacaoConta", b =>
                {
                    b.HasOne("TesteAplicacao.Entities.Conta", "conta")
                        .WithMany()
                        .HasForeignKey("conta_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesteAplicacao.Entities.Conta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("conta_id1");

                    b.Navigation("conta");
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("TesteAplicacao.Entities.Usuario", b =>
                {
                    b.Navigation("Conta")
                        .IsRequired();

                    b.Navigation("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
